=========================
time:2018-03-06 16:35:49,841 
logger:user 
level:ERROR 
file:log.py 
fun:error 
lineno:66 
message:Traceback (most recent call last):
  File "F:/git/myprojecttest\apptest\user.py", line 126, in getuserinfo
    user=  tmember.objects.filter(telephone=tele)[0]
  File "F:\git\myprojecttest\venv\lib\site-packages\django\db\models\query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

=========================
time:2018-03-06 16:41:07,555 
logger:user 
level:ERROR 
file:log.py 
fun:error 
lineno:66 
message:Traceback (most recent call last):
  File "F:\git\myprojecttest\apptest\user.py", line 127, in getuserinfo
    if userlist.count>0:
TypeError: '>' not supported between instances of 'method' and 'int'

=========================
time:2018-03-06 16:41:29,929 
logger:user 
level:ERROR 
file:log.py 
fun:error 
lineno:66 
message:Traceback (most recent call last):
  File "F:\git\myprojecttest\apptest\user.py", line 127, in getuserinfo
    if userlist.count>0:
TypeError: '>' not supported between instances of 'method' and 'int'

=========================
time:2018-03-06 16:41:36,243 
logger:user 
level:ERROR 
file:log.py 
fun:error 
lineno:66 
message:Traceback (most recent call last):
  File "F:\git\myprojecttest\apptest\user.py", line 127, in getuserinfo
    if userlist.count>0:
TypeError: '>' not supported between instances of 'method' and 'int'

=========================
time:2018-03-06 16:41:37,291 
logger:user 
level:ERROR 
file:log.py 
fun:error 
lineno:66 
message:Traceback (most recent call last):
  File "F:\git\myprojecttest\apptest\user.py", line 127, in getuserinfo
    if userlist.count>0:
TypeError: '>' not supported between instances of 'method' and 'int'

